package com.faster.fasterboot

import com.quantumn.ruleengine.bean.TradeAuditBo
global java.util.concurrent.ConcurrentHashMap<String,Long> scoreMap;

rule "ruleGroup1-txnaudit1"
    no-loop true
    agenda-group "ruleGroup1"
    when
        bo : TradeAuditBo(card=="001")
    then
        System.out.println("hit rule: group1-txnaudit1");
        Long score = (Long) scoreMap.getOrDefault("100");
        scoreMap.put("100",score+50L);

end

