package com.faster.fasterboot

import com.quantumn.ruleengine.bean.TradeAuditBo
import java.util.concurrent.ConcurrentHashMap
global java.util.concurrent.ConcurrentHashMap<String,Long> scoreMap;

rule "txnaudit1"
    no-loop true
    agenda-group "ruleGroup1"
    when
        bo : TradeAuditBo(card=="001" &&amount>5 && amount<30)
    then
        System.out.println("hit rule: txnaudit1");
        Long score = (Long) scoreMap.getOrDefault("100",0L);
        scoreMap.put("100",score+5L);
        System.out.println("score:"+scoreMap.get("100"));

end


rule "txnaudit2"
    no-loop true
    agenda-group "ruleGroup2"
    when
        not bo : TradeAuditBo(tradeTime>"01-Mar-2020" && tradeTime<"01-Jun-2020")
    then
        System.out.println("hit rule: txnaudit2");
        Long score = (Long) scoreMap.getOrDefault("100",0L);
        scoreMap.put("100",score+50L);
        System.out.println("score:"+scoreMap.get("100"));



end